/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentapp;
import java.awt.Color;
import java.awt.event.*;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author maciejszytow
 */
public class StudentFrame extends javax.swing.JFrame {

    /**
     * Creates new form StudentFrame
     */
    public StudentFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Header = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Freshman = new javax.swing.JRadioButton();
        Sophmore = new javax.swing.JRadioButton();
        Junior = new javax.swing.JRadioButton();
        Senior = new javax.swing.JRadioButton();
        addStudent = new javax.swing.JButton();

        buttonGroup1.add(Freshman);
        buttonGroup1.add(Sophmore);
        buttonGroup1.add(Junior);
        buttonGroup1.add(Senior);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Students Database");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximizedBounds(getMaximizedBounds());

        Header.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        Header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header.setText("Insert a new student");

        firstNameLabel.setText("First Name :");

        firstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameActionPerformed(evt);
            }
        });

        lastNameLabel.setText("Last Name:");

        jLabel1.setText("Grade:");

        Freshman.setText("Freshman");
        Freshman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FreshmanActionPerformed(evt);
            }
        });

        Sophmore.setText("Sophmore");
        Sophmore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SophmoreActionPerformed(evt);
            }
        });

        Junior.setText("Junior");
        Junior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JuniorActionPerformed(evt);
            }
        });

        Senior.setText("Senior");
        Senior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeniorActionPerformed(evt);
            }
        });

        addStudent.setText("Add ");
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(firstNameLabel)
                            .addComponent(jLabel1)
                            .addComponent(lastNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Freshman, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Junior, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Senior, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sophmore, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(firstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                .addComponent(lastName, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(addStudent))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstNameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Freshman)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sophmore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Junior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Senior)
                .addGap(47, 47, 47)
                .addComponent(addStudent)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String studentGrade;
    
    private void FreshmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FreshmanActionPerformed
        studentGrade = "Freshman";
    }//GEN-LAST:event_FreshmanActionPerformed
    
//    public void SophmoreActionPerformed(java.awt.event.ActionEvent evt) {                                         
//        System.out.println("Sophmore selected");
//    } 

    private void firstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameActionPerformed

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed
        String studentFirstName = firstName.getText();
        String studentLastName = lastName.getText();  
        while (!validate(studentFirstName, studentLastName)){
             JOptionPane.showMessageDialog(null, "Insert correct student's name");
             return;
        }
        String[] student = {studentFirstName, studentLastName, studentGrade};
        FileWriter fw = null;
        try {
          fw = new FileWriter("students.txt", true);
             } catch (IOException e) { 
           e.printStackTrace();
        }

        BufferedWriter bw = new BufferedWriter(fw);
        try {
          for (int i = 0; i < student.length; i++) {
            bw.write(student[i] + ", ");
          }
          bw.newLine();
        } catch (IOException e) {
           e.printStackTrace();
        }

        try {
           bw.close();
           fw.close();
        } catch (IOException e) {
           e.printStackTrace();
     }
        
        JOptionPane.showMessageDialog(null, "Student Added");
        firstName.setText("");
        lastName.setText("");
    }//GEN-LAST:event_addStudentActionPerformed

    private void SophmoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SophmoreActionPerformed
        studentGrade = "Sophmore";
    }//GEN-LAST:event_SophmoreActionPerformed

    private void JuniorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JuniorActionPerformed
        studentGrade = "Junior";
    }//GEN-LAST:event_JuniorActionPerformed

    private void SeniorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeniorActionPerformed
        studentGrade = "Senior";
    }//GEN-LAST:event_SeniorActionPerformed

    public boolean validate(String fn, String ln){
//        String m = "^[A-Z].[a-z]{2,}$";
        if (!fn.matches("^[A-Z].[a-z]{2,}$"))
                firstName.setBackground(new Color(255, 120, 120));
        if (!ln.matches("^[A-Z].[a-z]{2,}$"))
                lastName.setBackground(new Color(255, 120, 120));
        if (fn.matches("^[A-Z].[a-z]{2,}$"))
                firstName.setBackground(null);
        if (ln.matches("^[A-Z].[a-z]{2,}$"))
                lastName.setBackground(null);
        
        return fn.matches("^[A-Z].[a-z]{2,}$") && ln.matches("^[A-Z].[a-z]{2,}$");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(StudentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new StudentFrame().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Freshman;
    private javax.swing.JLabel Header;
    private javax.swing.JRadioButton Junior;
    private javax.swing.JRadioButton Senior;
    private javax.swing.JRadioButton Sophmore;
    private javax.swing.JButton addStudent;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lastName;
    private javax.swing.JLabel lastNameLabel;
    // End of variables declaration//GEN-END:variables
}
